/**:
  ros__parameters:
    allow_unsupported_version: true # flag to load unsupported format_version anyway. If true, just prints warning.
    center_line_resolution: 5.0         # [m]
    lanelet2_map_path: $(var lanelet2_map_path) # The lanelet2 map path
